name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H 68.168.211.152 >> ~/.ssh/known_hosts

    - name: Copy project files to server
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          --exclude 'venv' \
          --exclude 'db.sqlite3' \  
          ./ root@68.168.211.152:/root/webapps/sammy-mailer/

    - name: Run deploy commands on server
      run: |
        ssh root@68.168.211.152 << 'EOF'
          set -e
          cd /root/webapps/sammy-mailer

          echo "[✔] Creating venv if missing..."
          if [ ! -d "venv" ]; then
            python3 -m venv venv || {
              echo "❌ Failed to create virtual environment. Is python3-venv installed?"
              exit 1
            }
          fi

          echo "[✔] Installing/upgrading pip and requirements..."
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt

          echo "[✔] Running Django migrate and collectstatic..."
          ./venv/bin/python manage.py migrate --noinput
          ./venv/bin/python manage.py collectstatic --noinput

          echo "[✔] Restarting gunicorn..."
          pkill -f "gunicorn.*sammy-mailer" || echo "No existing gunicorn process to kill."

          nohup ./venv/bin/gunicorn application.wsgi:application \
              --bind 0.0.0.0:7000 \
              --workers 3 \
              --name sammy-mailer > gunicorn.log 2>&1 &

          echo "[✅] Deployment finished successfully."
        EOF
