name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # <== This fixes the shallow push issue

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}
        
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H 68.168.211.152 >> ~/.ssh/known_hosts

    - name: Push to remote bare git repo
      run: |
        git remote add production ssh://root@68.168.211.152:22/root/apps/sammy-mailer
        git push -f production main
